import express from 'express';
import indexRouter from './routes/index';
import healthRouter from './routes/health';
import aliveRouter from './routes/alive';
import versionRouter from './routes/version';
import metricsRouter from './routes/metrics';
import statusRouter from './routes/status';
import pingRouter from './routes/ping';
import readyRouter from './routes/ready';
import heartbeatRouter from './routes/heartbeat';
import pongRouter from './routes/pong';
import keepaliveRouter from './routes/keepalive';
import pulseRouter from './routes/pulse';
import uptimeRouter from './routes/uptime';
import awakeRouter from './routes/awake';
import alertRouter from './routes/alert';
import signalRouter from './routes/signal';
import welcomeRouter from './routes/welcome';
import beaconRouter from './routes/beacon';

const app = express();
app.use('/', indexRouter);
app.use('/health', healthRouter);
app.use('/alive', aliveRouter);
app.use('/version', versionRouter);
app.use('/metrics', metricsRouter);
app.use('/status', statusRouter);
app.use('/ping', pingRouter);
app.use('/ready', readyRouter);
app.use('/heartbeat', heartbeatRouter);
app.use('/pong', pongRouter);
app.use('/keepalive', keepaliveRouter);
app.use('/pulse', pulseRouter);
app.use('/uptime', uptimeRouter);
app.use('/awake', awakeRouter);
app.use('/alert', alertRouter);
app.use('/signal', signalRouter);
app.use('/welcome', welcomeRouter);
app.use('/beacon', beaconRouter);

export default app;
